### ISSUE TITLE
Route does not exists

### ISSUE THREAD

**Issue by gbrle** [prestaconcept/PrestaImageBundle#62]
Hello,

I have a routing problem. Error : 

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "presta_image_url_to_base64" as such route does not exist.").
```

`routing.yaml` : 
```
framework:
    router:
        utf8: true
presta_image:
    resource: '@PrestaImageBundle/Resources/config/ro
```

Ths  :)
